kind: pipeline
name: default

steps:

- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive --remote

- name: docker
  pull: if-not-exists
  image: plugins/docker
  settings:
    pull: false
    pull_image: false
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo:
      from_secret: docker_repo
    registry:
      from_secret: docker_registry

- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: drone_mail_host
    username:
      from_secret: drone_mail_user
    password:
      from_secret: drone_mail_password
    from: drone-noreply@binfalse.de
  when:
    status: [ success, failure ]

